### ISSUE TITLE
Set-cookie

### ISSUE THREAD

**Issue by tambovchanin** [olalonde/follow-redirects#11]
Not taken into account set-cookie from the server

**Comment by jamestalmage** [comment]
I'm sure that you've moved on in the past 18 months, but we are making progress.

See @cad6e81, there is now a `makeRequest` callback you can pass in to override [the default way](https://github.com/olalonde/follow-redirects/blob/0c27e5a467fe217b417afeeca657a2a1f4f44169/create.js#L70) we queue up the redirected request.

The callback gets three parameters.

 * `options` This is basically the options object you passed in merged with the newly requested URL, (note it's a parsed url object, not a string - see `url.parse` in Node core). You could create or update the `headers` parameter on that object to reflect any new cookie information.
 * `cb` The callback you need to pass along to `http[s].request`.
 * `res` The current result. This will be undefined if this is the initial request (i.e. we have not been redirected yet). If it is defined, then this is where you would find new cookies (`res.headers['set-cookie']`).

Here is [another example](https://github.com/olalonde/follow-redirects/blob/0c27e5a467fe217b417afeeca657a2a1f4f44169/test/lib/test-server.js#L51) from the test suite. It is not handling cookies, but rather setting up SSL certificates (which is only necessary because our test server uses a self signed certificate) and some inconsistencies in how node `0.8` and later versions handle the `http.Agent`. That aside, it still serves as a good example.

You will notice it uses two additional values from the `options` object.

* `options.nativeProtocol` - this is either nodes core `http` or `https` module, depending on which url we are being redirected to. You can think of it as the following:

  ```javascript
  if (options.protocol === `http:`) {
    options.nativeProtocol = require('http');
  } else if (options.protocol === `https:`) {
    options.nativeProtocol = require('https');
  }
  ```

* `options.defaultRequest` - this is simply the [default behavior](https://github.com/olalonde/follow-redirects/blob/0c27e5a467fe217b417afeeca657a2a1f4f44169/create.js#L70) I referenced above, if you only need to make minor modifications to the options object (updating the cookie header field for example), it is probably easiest to just update the headers field and then call this.

In the end, I kind of doubt we will implement a Cookie solution as part of `follow-redirects`, though we will likely make it easy to create a plugin that does. There would be no way for us to know exactly what you want us to do with those cookies as they got set (Are we saving them to a database?, etc.). 

I'm closing this as a "won't fix", for this particular project, but once the `makeRequest` API gets finalized, hopefully I can create a separate plugin that would help solve this.
