### ISSUE TITLE
project question

### ISSUE THREAD

**Issue by tarikjn** [olalonde/follow-redirects#33]
Hey there,

I like your approach to plug in at a low level with `http` and `https`. I want to take the same approach for client http caching. I've spent a fair amount of time searching and didn't find any existing module, apart from [cache-http](https://github.com/strongloop/cache-http) which has a weird API and only look at `If-Modified-Since`.

My question to you is are you aware of a library I may have missed and is there anything like `connect` but for http clients?

**Comment by jamestalmage** [comment]
Your best bet is to search using alternates to `npmjs.org` (`node-modules.org` is one). I've searched and haven't found one.

If you are going to tackle a caching implementation, a few pointers:

- use [`graceful-fs`](https://www.npmjs.com/package/graceful-fs) instead of just `fs` (anything that uses it under the hood is probably fine too). You will have hard to trace errors otherwise.
- checkout [`hasha`](https://github.com/sindresorhus/hasha) or [`md5-hex`](https://github.com/sindresorhus/md5-hex) for easy ways to hash cache keys.
- checkout [`package-hash`](https://github.com/novemberborn/package-hash) for an interesting take on invalidating your cache keys with version upgrades (major feature is it works with live changes and `npm link`).

Most of these recommendations are born from experience while developing [`caching-transform`](https://github.com/jamestalmage/caching-transform) to speed up [AVA](https://github.com/sindresorhus/ava). (Also, you should definitely use AVA to test this, since there will likely be some IO involved, it will make things speedy).

**Comment by tarikjn** [comment]
Those are some interesting notes, thank you! I'll look at each in more details, and have already started compiling some notes of my own. For `graceful-fs` it's unlikely that I'll use the filesystem, I'll probably provide a store API and a default store which is in-memory and based on one of the `LRU` implementations available on npm. I think [node-cacher](https://github.com/addisonj/node-cacher), a server cache, provides a very good example of how to split and document cache and store. The in-memory nature would solve the concern of invalidating on updates, which could then be addressed either by the persistent stores themselves or triggered on the store API by an update on the cache package.

**Comment by olalonde** [comment]
https://github.com/maxogden/abstract-blob-store would be a good way to abstract the persistence layer too

**Comment by tarikjn** [comment]
@olalonde nice! That's even better.

**Comment by olalonde** [comment]
@tarikjn I don't think there's a particular reason other than no one has taken the time to write implementations for them :)

**Comment by tarikjn** [comment]
In regard to using something modular a bit like `connect`, have you guys considered using [http.Agent](https://nodejs.org/api/http.html#http_class_http_agent) instead of overwriting `http`/`https`? One inconvenient I see to using http.Agent would be how to combine multiple agents together?

**Comment by jamestalmage** [comment]
I'm closing this as it isn't really a `follow-redirects` issue. If you do create such an implementation, please let us know. Maybe we can cross-link in our respective README's, and add a few tests for people who want to use `caching` and `follow-redirects` behavior together.

**Comment by olalonde** [comment]
@tarikjn not sure if it helps but I just released this module which might help with caching: https://github.com/blockai/persistent-memoize
